// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctsutqwvmszoblrkmlac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0c3V0cXd2bXN6b2JscmttbGFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODgyNDcsImV4cCI6MjA3MTM2NDI0N30.N0Pb-Z94aKhb6AQZt03DdZksoc3wV1TlYqqLGHAnzbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});